server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  datasource:
    dynamic: # 多数据源配置
      primary: master
      datasource:
        master:
          # MYSQL数据库
          name: gitee_jeelowcode
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.master.name}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true # MySQL Connector/J 8.X 连接的示例
          username: root
          password: 123456
        slave: # 日志库单独
          name: gitee_jeelowcodelog
          lazy: true # 开启懒加载，保证启动速度
          url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.dynamic.datasource.slave.name}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          username: root
          password: 123456

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 127.0.0.1  # 地址
    port: 6379 # 端口
    database: 9 # 数据库索引
    #password: 123456 # 密码，建议生产环境开启

jeelowcode:
  excludeTableNames: #不允许该类型的表开头
    - lowcode_
    - qrtz_
    - system_
    - act_
    - bpm_
    - flw_
    - infra_
  debug: true #是否开启调试模式5
  #AES加解密 key 重新生成AesUtil.genAesKey()
  aesKey: O2BEeIv399qHQNhD6aGW8R8DEj4bqHXm
